apiVersion: v1
kind: Service
metadata:
  name: cosmollm
spec:
  ports:
    - name: cosmollm
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: cosmollm
  type: ClusterIP
