apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    deploymentId: {{ID}}
  name: cosmollm-experiment-volume-{{ID}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{STORAGE_CLASS}}
  resources:
    requests:
      storage: {{STORAGE_SIZE}}
