apiVersion: v1
kind: Service
metadata:
  name: cosmollm-gui-{{ID}}
spec:
  ports:
    - name: cosmollm-gui
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: cosmollm-gui-{{ID}}
  type: ClusterIP
