apiVersion: v1
kind: Service
metadata:
  name: cosmollm-compute-{{ID}}-{{COMPUTE_ID}}
spec:
  ports:
    - name: cosmollm-compute
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    app: cosmollm-compute-{{ID}}-{{COMPUTE_ID}}
  type: ClusterIP
