apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: cosmollm-admin
spec:
  rules:
    - host: {{DOMAIN}}
      http:
        paths:
          - backend:
              service:
                name: cosmollm-admin
                port:
                  number: 8000
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{DOMAIN}}
      secretName: {{DOMAIN}}-tls
