apiVersion: v1
kind: Service
metadata:
  name: cosmollm-admin
spec:
  ports:
    - name: cosmollm-admin
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: cosmollm-admin
  type: ClusterIP
